<?xml version="1.0"?>
<!DOCTYPE softwarelist [
	<!ELEMENT softwarelist (software+)>
		<!ATTLIST softwarelist name CDATA #REQUIRED>
		<!ATTLIST softwarelist description CDATA #IMPLIED>
		<!ELEMENT software (description, year?, publisher, part*)>
			<!ATTLIST software name CDATA #REQUIRED>
			<!ATTLIST software cloneof CDATA #IMPLIED>
			<!ATTLIST software supported (yes|partial|no) "yes">
			<!ELEMENT description (#PCDATA)>
			<!ELEMENT year (#PCDATA)>
			<!ELEMENT publisher (#PCDATA)>
			<!ELEMENT part (dataarea*)>
				<!ATTLIST part name CDATA #REQUIRED>
				<!ATTLIST part interface CDATA #REQUIRED>
				<!-- feature is used to store things like pcb-type, mapper type, etc. Specific values depend on the system. -->
				<!ATTLIST part feature CDATA #IMPLIED>
				<!ELEMENT dataarea (rom*)>
					<!ATTLIST dataarea name CDATA #REQUIRED>
					<!ATTLIST dataarea size CDATA #REQUIRED>
					<!ATTLIST dataarea databits (8|16|32|64) "8">
					<!ATTLIST dataarea endian (big|little) "little">
					<!ELEMENT rom EMPTY>
						<!ATTLIST rom name CDATA #IMPLIED>
						<!ATTLIST rom size CDATA #REQUIRED>
						<!ATTLIST rom crc CDATA #IMPLIED>
						<!ATTLIST rom md5 CDATA #IMPLIED>
						<!ATTLIST rom sha1 CDATA #IMPLIED>
						<!ATTLIST rom offset CDATA #IMPLIED>
						<!ATTLIST rom status (baddump|nodump|good) "good">
						<!ATTLIST rom loadflag (load16_byte|load16_word|load16_word_swap|load32_byte|load32_word|load32_word_swap|load32_dword|load64_word|load64_word_swap|reload) #IMPLIED>
]>
<softwarelist name="pv1000" description="Casio PV-1000 cartridges">
	<!-- GPA-104 -->
	<software name="amidar">
		<description>Amidar</description>
		<year>1982</year>
		<publisher>Casio</publisher>
		<part name="cart" interface="pv1000_cart">
			<dataarea name="rom" size="8192">
				<rom name="amidar.bin" size="8192" crc="c82628cc" sha1="00322d4025fef19728194442f9e06a4cccd01933" offset="0000" />
			</dataarea>
		</part>
	</software>

	<!-- GPA-115 -->
	<software name="excitemj">
		<description>Excite Mahjong</description>
		<year>1982</year>
		<publisher>Casio</publisher>
		<part name="cart" interface="pv1000_cart">
			<dataarea name="rom" size="16384">
				<rom name="excitemj.bin" size="16384" crc="0d2f829c" sha1="6cc9e5d234bc1b483108ae4dc79d644802a64ef0" offset="0000" />
			</dataarea>
		</part>
	</software>

	<!-- GPA-101 -->
	<software name="pooyan">
		<description>Pooyan</description>
		<year>1982</year>
		<publisher>Casio</publisher>
		<part name="cart" interface="pv1000_cart">
			<dataarea name="rom" size="8192">
				<rom name="pooyan.bin" size="8192" crc="bd6edc48" sha1="606b7d603da23e70012b361d7ffb53ea026f88f5" offset="0000" />
			</dataarea>
		</part>
	</software>

<!--
	/* Super Cobra GPA-102 */
	/* Tutankham GPA-103 */
	/* Dig Dug GPA-105 */
	/* Warp & Warp GPA-106 */
	/* Turpin GPA-107 */
	/* GPA-108 */
	/* Pachinko-UFO GPA-109 */
	/* Fighting Bug GPA-110 */
	/* Space Panic GPA-111 */
	/* Naughty Boy GPA-112 */
	/* GPA-113 */
	/* Dirty Chameleon GPA-114 */
-->

</softwarelist>
