<?xml version="1.0"?>
<!DOCTYPE softwarelist [
	<!ELEMENT softwarelist (software+)>
		<!ATTLIST softwarelist name CDATA #REQUIRED>
		<!ATTLIST softwarelist description CDATA #IMPLIED>
		<!ELEMENT software (description, year?, publisher, part*)>
			<!ATTLIST software name CDATA #REQUIRED>
			<!ATTLIST software cloneof CDATA #IMPLIED>
			<!ATTLIST software supported (yes|partial|no) "yes">
			<!ELEMENT description (#PCDATA)>
			<!ELEMENT year (#PCDATA)>
			<!ELEMENT publisher (#PCDATA)>
			<!ELEMENT part (dataarea*)>
				<!ATTLIST part name CDATA #REQUIRED>
				<!ATTLIST part interface CDATA #REQUIRED>
				<!-- feature is used to store things like pcb-type, mapper type, etc. Specific values depend on the system. -->
				<!ATTLIST part feature CDATA #IMPLIED>
				<!ELEMENT dataarea (rom*)>
					<!ATTLIST dataarea name CDATA #REQUIRED>
					<!ATTLIST dataarea size CDATA #REQUIRED>
					<!ATTLIST dataarea databits (8|16|32|64) "8">
					<!ATTLIST dataarea endian (big|little) "little">
					<!ELEMENT rom EMPTY>
						<!ATTLIST rom name CDATA #IMPLIED>
						<!ATTLIST rom size CDATA #REQUIRED>
						<!ATTLIST rom crc CDATA #IMPLIED>
						<!ATTLIST rom md5 CDATA #IMPLIED>
						<!ATTLIST rom sha1 CDATA #IMPLIED>
						<!ATTLIST rom offset CDATA #IMPLIED>
						<!ATTLIST rom status (baddump|nodump|good) "good">
						<!ATTLIST rom loadflag (load16_byte|load16_word|load16_word_swap|load32_byte|load32_word|load32_word_swap|load32_dword|load64_word|load64_word_swap|reload) #IMPLIED>
]>
<softwarelist name="scv" description="Epoch Super Cassette Vision cartridges">
	<software name="astrwrs">
		<description>Astro Wars - Invaders from Space</description>
		<year>1984</year>
		<publisher>Epoch</publisher>
		<part name="cart" interface="scv_cart">
			<dataarea name="rom" size="8192">
				<rom name="astrwrs.bin" size="8192" crc="2dbdb166" sha1="53a9a308b6f0bcb2137704f70657698719551b5e" offset="0000" />
			</dataarea>
		</part>
	</software>

	<!-- bad dump, refuses to work on real h/w -->
	<software name="astrwrs2">
		<description>Astro Wars II - Battle in Galaxy</description>
		<year>1984</year>
		<publisher>Epoch</publisher>
		<part name="cart" interface="scv_cart">
			<dataarea name="rom" size="8192">
				<rom name="astrwrs2.bin" size="8192" crc="19056c71" sha1="7b1073339a4641d4e0f00b284c64fc3c6d385b7c" offset="0000" status="baddump" />
			</dataarea>
		</part>
	</software>

	<!-- name taken from boxart -->
	<software name="baseball">
		<description>Super Baseball</description>
		<year>1984</year>
		<publisher>Epoch</publisher>
		<part name="cart" interface="scv_cart">
			<dataarea name="rom" size="16384">
				<rom name="baseball.bin" size="16384" crc="56f1c473" sha1="37a1dce6c1921950c588d6492cd1b57feb615175" offset="0000" />
			</dataarea>
		</part>
	</software>

	<software name="bouldash">
		<description>Boulder Dash</description>
		<year>1985</year>
		<publisher>Epoch></publisher>
		<part name="cart" interface="scv_cart">
			<dataarea name="rom" size="16384">
				<rom name="boulder_dash.bin" size="16384" crc="e045884c" sha1="55942e5b7824314b072b7b40c6b72db0d5404189" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="comicirc">
		<description>Comic Circus</description>
		<year>1985</year>
		<publisher>Epoch</publisher>
		<part name="cart" interface="scv_cart">
			<dataarea name="rom" size="16384">
				<rom name="comic_circus.bin" size="16384" crc="ea55faed" sha1="2e4ceb2bf68d26c263c3d1c63f7e2143ef2355bc" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="elevfght">
		<description>Elevator Fight</description>
		<year>1984</year>
		<publisher>Epoch</publisher>
		<part name="cart" interface="scv_cart">
			<dataarea name="rom" size="16384">
				<rom name="elevfght.bin" size="16384" crc="72dd6031" sha1="8b2c185408309ee1e75d40299c003041db17b133" offset="0000" />
			</dataarea>
		</part>
	</software>

	<software name="minr2049">
		<description>Miner 2049er</description>
		<year>1985</year>
		<publisher>Epoch</publisher>
		<part name="cart" interface="scv_cart">
			<dataarea name="rom" size="16384">
				<rom name="miner_2049er.bin" size="16384" crc="b0ffc6e2" sha1="0414878f4aedade180b273257497c1d11cdccb2f" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="nebula">
		<description>Nebula</description>
		<year>1984</year>
		<publisher>Epoch</publisher>
		<part name="cart" interface="scv_cart">
			<dataarea name="rom" size="16384">
				<rom name="nebula.bin" size="16384" crc="5e6a4caf" sha1="699eaf434e73a42e71adf52426b22f0dd85e2897" offset="0000" />
			</dataarea>
		</part>
	</software>

	<software name="popchips">
		<description>Pop and Chips</description>
		<year>198?</year>
		<publisher>Epoch</publisher>
		<part name="cart" interface="scv_cart">
			<!-- 8kb RAM -->
			<dataarea name="rom" size="32768">
				<rom name="popchips.bin" size="32768" crc="cc4fb04d" sha1="5979abd6051d531eafe1ea3b37c97ce2e3e97f8e" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="punchboy">
		<description>Punch Boy</description>
		<year>1984</year>
		<publisher>Epoch</publisher>
		<part name="cart" interface="scv_cart">
			<dataarea name="rom" size="16384">
				<rom name="punchboy.bin" size="16384" crc="4107f03a" sha1="e7391c71ba7deede3db22191ea058ccf429d7bb5" offset="0000" />
			</dataarea>
		</part>
	</software>

	<software name="rgmahjon">
		<description>Real Graphic Mahjongg</description>
		<year>1984</year>
		<publisher>Epoch</publisher>
		<part name="cart" interface="scv_cart">
			<dataarea name="rom" size="16384">
				<rom name="real_graphic_mahjong.bin" size="16384" crc="d3d9106c" sha1="7190ff2944c1ffbde6866e720417b86b3844ffa2" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="sansupyu">
		<description>Sansupyuta/Super Professor</description>
		<year>1985</year>
		<publisher>Epoch</publisher>
		<part name="cart" interface="scv_cart">
			<dataarea name="rom" size="32768">
				<rom name="sansupyuta.bin" size="32768" crc="6e7e01b5" sha1="dc05257c831cffa5ec66302c88e1d45a92c6dc9c" offset="0" />
			</dataarea>
		</part>
	</software>

	<!-- jpn cart, name taken from boxart -->
	<software name="soccer">
		<description>Super Soccer</description>
		<year>1985</year>
		<publisher>Epoch</publisher>
		<part name="cart" interface="scv_cart">
			<dataarea name="rom" size="16384">
				<rom name="soccer.bin" size="16384" crc="8283907c" sha1="61e4b8e43cc593b3a2e838c08f6dad6cca77d712" offset="0000" />
			</dataarea>
		</part>
	</software>

	<!-- maybe pal, name taken from boxart -->
	<software name="soccera" cloneof="soccer">
		<description>Super Soccer (alt)</description>
		<year>1985</year>
		<publisher>Epoch</publisher>
		<part name="cart" interface="scv_cart">
			<dataarea name="rom" size="16384">
				<rom name="soccera.bin" size="16384" crc="590eeefd" sha1="951ecd2a1d2e7d900c13e91ff028723a9df9e60e" offset="0000" />
			</dataarea>
		</part>
	</software>

	<!-- name taken from boxart -->
	<software name="suprgolf">
		<description>Super Golf</description>
		<year>1984</year>
		<publisher>Epoch</publisher>
		<part name="cart" interface="scv_cart">
			<dataarea name="rom" size="16384">
				<rom name="suprgolf.bin" size="16384" crc="0c0581c9" sha1="2d3ab09907a4a9c5d66306f316c7211f498cbcc2" offset="0000" />
			</dataarea>
		</part>
	</software>

	<software name="wheelrcr">
		<description>Wheelie Racer</description>
		<year>1985</year>
		<publisher>Epoch</publisher>
		<part name="cart" interface="scv_cart">
			<dataarea name="rom" size="16384">
				<rom name="wheelrcr.bin" size="16384" crc="9d9b29db" sha1="479f767384e7b7bfe58eeadd67dbe642fe8a2fcf" offset="0000" />
			</dataarea>
		</part>
	</software>

<!--
	/* Basic Nyuumon */
	/* Doraemon */
	/* Dragon Ball */
	/* Dragon Slayer */
	/* Lupin III */
	/* Mappy */
	/* Milky Princess */
	/* Nekketsu Kung Fu Road */
	/* Pole Position II */
	/* Rantou Pro Wrestling */
	/* Shogi Nyuumon */
	/* Sky Kid */
	/* Star Speeder */
	/* Ton Ton Ball */
	/* Wai Wai Monster Land */
-->

</softwarelist>
